apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base # This points back to the folder we made in Step 1
namePrefix: staging-
namespace: staging # Requirement for separate namespace
